// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcUVF5FUavJX7Tl1Jd_9b99G0OeWQyIMM',
    appId: '1:52591216815:web:d7ff4c06c8e7c4ded32c5a',
    messagingSenderId: '52591216815',
    projectId: 'app-dev-ad719',
    authDomain: 'app-dev-ad719.firebaseapp.com',
    storageBucket: 'app-dev-ad719.firebasestorage.app',
    measurementId: 'G-TY1P5373Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASSgeHzfznedvfkFBJ-1z1Nwq0pn-iltU',
    appId: '1:52591216815:android:066a912b28c88edbd32c5a',
    messagingSenderId: '52591216815',
    projectId: 'app-dev-ad719',
    storageBucket: 'app-dev-ad719.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCzfli2WExejdz-ihz3l72NycM0E1kWLo',
    appId: '1:52591216815:ios:83070d96eeabd282d32c5a',
    messagingSenderId: '52591216815',
    projectId: 'app-dev-ad719',
    storageBucket: 'app-dev-ad719.firebasestorage.app',
    iosBundleId: 'com.example.appStarterKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCzfli2WExejdz-ihz3l72NycM0E1kWLo',
    appId: '1:52591216815:ios:83070d96eeabd282d32c5a',
    messagingSenderId: '52591216815',
    projectId: 'app-dev-ad719',
    storageBucket: 'app-dev-ad719.firebasestorage.app',
    iosBundleId: 'com.example.appStarterKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcUVF5FUavJX7Tl1Jd_9b99G0OeWQyIMM',
    appId: '1:52591216815:web:30553ac9382aa1f3d32c5a',
    messagingSenderId: '52591216815',
    projectId: 'app-dev-ad719',
    authDomain: 'app-dev-ad719.firebaseapp.com',
    storageBucket: 'app-dev-ad719.firebasestorage.app',
    measurementId: 'G-BREX04FG4X',
  );
}