import 'package:flutter/material.dart';

class AppColors {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF4F46E5),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFE0E7FF),
      onPrimaryContainer: Color(0xFF1E1B4B),
      secondary: Color(0xFF0D9488),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFCCFBF1),
      onSecondaryContainer: Color(0xFF134E4A),
      tertiary: Color(0xFFF59E0B),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFEF3C7),
      onTertiaryContainer: Color(0xFF78350F),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFEE2E2),
      onErrorContainer: Color(0xFF991B1B),
      surface: Color(0xFFF8FAFC),
      onSurface: Color(0xFF0F172A),
      onSurfaceVariant: Color(0xFF475569),
      outline: Color(0xFFCBD5E1),
      outlineVariant: Color(0xFFE2E8F0),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF1E293B),
      inversePrimary: Color(0xFF818CF8),
      primaryFixed: Color(0xFFE0E7FF),
      onPrimaryFixed: Color(0xFF1E1B4B),
      primaryFixedDim: Color(0xFFC7D2FE),
      onPrimaryFixedVariant: Color(0xFF3730A3),
      secondaryFixed: Color(0xFFCCFBF1),
      onSecondaryFixed: Color(0xFF134E4A),
      secondaryFixedDim: Color(0xFF99F6E4),
      onSecondaryFixedVariant: Color(0xFF115E59),
      tertiaryFixed: Color(0xFFFEF3C7),
      onTertiaryFixed: Color(0xFF78350F),
      tertiaryFixedDim: Color(0xFFFDE68A),
      onTertiaryFixedVariant: Color(0xFF92400E),
      surfaceDim: Color(0xFFE2E8F0),
      surfaceBright: Color(0xFFF8FAFC),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF1F5F9),
      surfaceContainer: Color(0xFFEFF3F8),
      surfaceContainerHigh: Color(0xFFE8EDF3),
      surfaceContainerHighest: Color(0xFFE2E8F0),
      surfaceTint: Color(0xFF4F46E5),
    );
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF818CF8),
      onPrimary: Color(0xFF1E1B4B),
      primaryContainer: Color(0xFF3730A3),
      onPrimaryContainer: Color(0xFFE0E7FF),
      secondary: Color(0xFF2DD4BF),
      onSecondary: Color(0xFF134E4A),
      secondaryContainer: Color(0xFF115E59),
      onSecondaryContainer: Color(0xFFCCFBF1),
      tertiary: Color(0xFFFBBF24),
      onTertiary: Color(0xFF78350F),
      tertiaryContainer: Color(0xFF92400E),
      onTertiaryContainer: Color(0xFFFEF3C7),
      error: Color(0xFFF87171),
      onError: Color(0xFF7F1D1D),
      errorContainer: Color(0xFF991B1B),
      onErrorContainer: Color(0xFFFEE2E2),
      surface: Color(0xFF0F172A),
      onSurface: Color(0xFFF1F5F9),
      onSurfaceVariant: Color(0xFF94A3B8),
      outline: Color(0xFF475569),
      outlineVariant: Color(0xFF334155),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFF1F5F9),
      inversePrimary: Color(0xFF4F46E5),
      primaryFixed: Color(0xFFE0E7FF),
      onPrimaryFixed: Color(0xFF1E1B4B),
      primaryFixedDim: Color(0xFFC7D2FE),
      onPrimaryFixedVariant: Color(0xFF3730A3),
      secondaryFixed: Color(0xFFCCFBF1),
      onSecondaryFixed: Color(0xFF134E4A),
      secondaryFixedDim: Color(0xFF99F6E4),
      onSecondaryFixedVariant: Color(0xFF115E59),
      tertiaryFixed: Color(0xFFFEF3C7),
      onTertiaryFixed: Color(0xFF78350F),
      tertiaryFixedDim: Color(0xFFFDE68A),
      onTertiaryFixedVariant: Color(0xFF92400E),
      surfaceDim: Color(0xFF0F172A),
      surfaceBright: Color(0xFF334155),
      surfaceContainerLowest: Color(0xFF020617),
      surfaceContainerLow: Color(0xFF0F172A),
      surfaceContainer: Color(0xFF1E293B),
      surfaceContainerHigh: Color(0xFF273449),
      surfaceContainerHighest: Color(0xFF334155),
      surfaceTint: Color(0xFF818CF8),
    );
  }

  static const success = Color(0xFF16A34A);
  static const successContainer = Color(0xFFDCFCE7);
  static const onSuccess = Color(0xFF166534);
  static const warning = Color(0xFFF59E0B);
  static const warningContainer = Color(0xFFFEF3C7);
  static const onWarning = Color(0xFF92400E);
}
